name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #      Checkout downloads a copy of this repo on the runner
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      #          This will save the contents of this local Maven repository, located in the .m2 directory of the runner's home directory.
      #          The cache key will be the hashed contents of pom.xml, so changes to pom.xml will invalidate the cache.
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn --batch-mode -Dspring.profiles.active=ci --update-snapshots verify
